# Date:2017/6/8 2:21
# Author:HuWenjie<1@hwj.me>
# Ghost Bird File System Reader
# Makefile
# 
# BSD 2-Clause License
# 
# Copyright (c) 2017, Ghost Bird Operating System Project Developers.
# All rights reserved.

LDFLAGS := -Wall -O2
CFLAGS := -I C:/MinGW/include

all:
	$(CC) gfr.c -o gfr.exe $(LDFLAGS) $(CFLAGS)
	
clean:
	$(RM) gfr.exe
