# Date:Miss
# Author:HuWenjie<1@hwj.me>
# Explorer Loader
# makefile for Explorer Loader
# 
# BSD 2-Clause License
# 
# Copyright (c) 2017, Ghost Bird Operating System Project Developers.
# All rights reserved.

# There are some command different among OS


all:
	cd mbr && make all
	cd boot && make all
	
install:
	cd mbr && make install
	cd boot && make install
	
clean:
	cd mbr && make clean
	cd boot && make clean
	
	
# part of functions
	




	
